micronaut:
  application:
    name: key-manager-grpc
  http:
    services:
      erp-itau:
        urls:
          - http://localhost:9091
        read-timeout: 5s
        pool:
          enabled: true
          max-connections: 50

datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/pix_key_manager`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:ajudazupper}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update