micronaut:
  application:
    name: key-manager-grpc
  http:
    services:
      erp-itau:
        urls:
          - ${ERP_ITAU_URL:`http://localhost:9091`}
        read-timeout: 5s
        pool:
          enabled: true
          max-connections: 50
      bcb:
        urls:
          - ${BCB_URL:`http://localhost:8082`}
        read-timeout: 5s
        pool:
          enabled: true
          max-connections: 50

datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/pix_key_manager`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:ajudazupper}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update